apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels: { app: redis }
spec:
  replicas: 1
  selector: { matchLabels: { app: redis } }
  template:
    metadata:
      labels: { app: redis }
    spec:
      serviceAccountName: ticketing-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        seccompProfile: { type: RuntimeDefault }
      containers:
        - name: redis
          image: redis:7-alpine
          args: ["redis-server","--save","","--appendonly","no"]
          ports: [{ containerPort: 6379 }]
          readinessProbe:
            exec: { command: ["redis-cli","ping"] }
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            exec: { command: ["redis-cli","ping"] }
            initialDelaySeconds: 10
            periodSeconds: 10
          resources: {{ .Values.redis.resources | toYaml | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: { drop: ["ALL"] }
---
apiVersion: v1
kind: Service
metadata: { name: redis }
spec:
  selector: { app: redis }
  ports: [{ port: 6379, targetPort: 6379 }]
