apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels: { app: worker }
spec:
  replicas: {{ .Values.worker.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxUnavailable: 0, maxSurge: 1 }
  selector: { matchLabels: { app: worker } }
  template:
    metadata:
      labels: { app: worker }
    spec:
      serviceAccountName: ticketing-sa
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile: { type: RuntimeDefault }
      containers:
        - name: worker
          image: {{ include "ticketing.image" (dict "root" . "name" "worker") }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef: { name: ticketing-config }
          env:
            - { name: POSTGRES_USER,     valueFrom: { secretKeyRef: { name: ticketing-secret, key: POSTGRES_USER } } }
            - { name: POSTGRES_PASSWORD, valueFrom: { secretKeyRef: { name: ticketing-secret, key: POSTGRES_PASSWORD } } }
          livenessProbe:
            exec: { command: ["sh","-c","pgrep -f worker.js || exit 1"] }
            initialDelaySeconds: 15
            periodSeconds: 20
          resources: {{ .Values.worker.resources | toYaml | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: { drop: ["ALL"] }
